# Generated by Django 3.0.8 on 2020-07-25 00:13

from django.db import migrations

def create_data(apps, schema_editor):
    Student = apps.get_model('students', 'Student')
    Student(name="Luis Cobas", email="luisma.cobas@gmail.com", document="22342342", phone="3773206025").save()

class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]